/* 
 * File:   MacroTrigram.h
 * Author: tsa
 *
 * Created on 21 juin 2012, 20:20
 */

#ifndef MACROTRIGRAM_H
#define	MACROTRIGRAM_H

#define SEP "_"

#define ID SEP "ID"

#define TRIGRAM_USER_FIELD "UFI"
#define TRIGRAM_WIDGET_TYPE "WTY"
#define TRIGRAM_USER_ROLE "URO"
#define TRIGRAM_USER_RIGHT "URI"
#define TRIGRAM_SPACE "SPA"
#define TRIGRAM_ACCESS_CONTROL_LIST "ACL"
#define TRIGRAM_INFORMATION_UNIT "INU"
#define TRIGRAM_INFORMATION_SUB_UNIT "ISU"
#define TRIGRAM_INFORMATION_UNIT_TYPE "IUT"
#define TRIGRAM_USER "USR"
#define TRIGRAM_USER_HISTORICAL_ACTION "UHA"
#define TRIGRAM_USER_HIERARCHY "UHI"
#define TRIGRAM_USER_PROFILE "UPR"
#define TRIGRAM_USER_VALUE "UVA"
#define TRIGRAM_ALERT_PARAM "APA"
#define TRIGRAM_ALERT "ALE"
#define TRIGRAM_ALERT_SEQUENCE "ASE"
#define TRIGRAM_USER_ACTION "UAC"
#define TRIGRAM_ADDON "ADO"
#define TRIGRAM_ALERT_ACKNOWLEDGE "ACK"
#define TRIGRAM_ALERT_MEDIA_SPECIALIZATION "AMS"
#define TRIGRAM_ALERT_VALUE "AVA"
#define TRIGRAM_ALERT_TRACKING "ATR"
#define TRIGRAM_ALERT_TRACKING_EVENT "ATE"
#define TRIGRAM_ENGINE "ENG"
#define TRIGRAM_TAB "TAB"
#define TRIGRAM_TAB_VERSION "TVS"
#define TRIGRAM_WIDGET "WGT"
#define TRIGRAM_PLUGIN "PLG"
#define TRIGRAM_ORGANIZATION "ORG"
#define TRIGRAM_ORGANIZATION_TYPE "OTY"
#define TRIGRAM_ORGANIZATION_VALUE "OVA"
#define TRIGRAM_ORGANIZATION_FIELD "OFI"
#define TRIGRAM_INFORMATION "INF"
#define TRIGRAM_INFORMATION_VALUE "IVA"
#define TRIGRAM_INFORMATION_HISTORICAL_VALUE "IHV"
#define TRIGRAM_ALERT_CRITERIA "ACR"
#define TRIGRAM_PROBE "PRB"
#define TRIGRAM_PROBE_PACKAGE "PPA"
#define TRIGRAM_PROBE_PACKAGE_PARAMETER "PPP"
#define TRIGRAM_SOURCE "SRC"
#define TRIGRAM_SOURCE_PARAMETER "SRP"
#define TRIGRAM_SOURCE_PARAMETER_VALUE "SPV"
#define TRIGRAM_ASSET "AST"
#define TRIGRAM_ASSET_ARCHITECTURE "ASA"
#define TRIGRAM_ASSET_DISTRIBUTION "ASD"
#define TRIGRAM_ASSET_RELEASE "ASR"
#define TRIGRAM_SYSLOG "SLO"
#define TRIGRAM_SYSLOG_HISTORY "SLH"
#define TRIGRAM_SEARCH "SEA"
#define TRIGRAM_SEARCH_TYPE "STY"
#define TRIGRAM_SEARCH_PARAMETER "SEP"
#define TRIGRAM_SEARCH_PARAMETER_VALUE "SEV"
#define TRIGRAM_SEARCH_UNIT "SEU"
#define TRIGRAM_PACK "PCK"
#define TRIGRAM_PACK_OPTION "POP"
#define TRIGRAM_OPTION_VALUE "OPV"        
#define TRIGRAM_OPTION "OPT"
#define TRIGRAM_MEDIA "MED"
#define TRIGRAM_MEDIA_VALUE "MEV"


#define TEMPLATE_TRIGRAM(CLASS, TRIGRAM) template<> \
        struct dbo_traits<CLASS> : public dbo_default_traits \
        { \
            static const char *surrogateIdField() \
            { \
                return TRIGRAM; \
            } \
        };
        

#endif	/* MACROTRIGRAM_H */

